import type { Metadata } from "next";
import { Cormorant_Garamond, Manrope } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { JsonLd } from "@/components/seo/json-ld";
import { buildBusinessSchema, buildWebSiteSchema } from "@/lib/business-data";
import "./globals.css";

const displayFont = Cormorant_Garamond({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const bodyFont = Manrope({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://epicmob.ro"),
  title: {
    default: "Epic Mob Atelier — Mobilier la comandă",
    // Child pages set just their descriptive part; the brand is appended here.
    template: "%s | Epic Mob",
  },
  description:
    "Mobilier premium la comandă, consultanță și execuție cap-coadă pentru proiecte rezidențiale.",
  // Default social-share metadata; child pages override title/description/images.
  // The branded default image is generated by app/opengraph-image.tsx.
  openGraph: {
    type: "website",
    siteName: "Epic Mob",
    locale: "ro_RO",
    url: "/",
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ro"
      className={`${displayFont.variable} ${bodyFont.variable} h-full scroll-smooth`}
    >
      <body className="min-h-full bg-bg text-navy antialiased">
        <JsonLd data={buildBusinessSchema()} />
        <JsonLd data={buildWebSiteSchema()} />
        <SiteHeader />
        <div className="relative">{children}</div>
        <SiteFooter />
        <Analytics />
      </body>
    </html>
  );
}
